### ISSUE TITLE
Create a login page

### ISSUE THREAD

**Issue by HKGx** [nutrishare/nutrishare#2]
Something basic will suffice, as of #8 we can easily use vite and react for doing the client side job

**Comment by Daste745** [comment]
This was implemented in a very basic manner in #6.

We'll have to create something more user-friendly once we have a basic page layout. But I think the current implementation will suffice for now. What do you think @HKGx? Can we close this along with #6?

**Comment by HKGx** [comment]
@Daste745 it's alright to close this along with #6. we can always spawn a new task with improvements. :)
